#try:
#    print(num)
#except IOError:
#    print('产生错误了')
try:
    print(num)
except NameError:
    print('产生错误了')